services:
  - type: web
    name: blog-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://mern-mini-blog-task.onrender.com 